language: python

arch:
  - arm64

services:
  - docker

python:
  - "2.7"
  - "3.6"

before_install:
  - docker pull schachr/raspbian-stretch:latest
  - docker run --name raspbian -it schachr/raspbian-stretch:latest /bin/bash
  - uname -a
  - sudo apt-get install -y \
    libjpeg-dev libpng-dev libtiff-dev libgtk-3-dev \
    libavcodec-extra libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjasper1 libjasper-dev \
    libatlas-base-dev gfortran libeigen3-dev libtbb-dev \
    python-dev python-numpy python-pytest

script:
  - cd tests/python
  - pytest tests.py
