language: python

arch:
  - arm64

python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get install -y \
    libjpeg-dev libpng-dev libtiff-dev libgtk-3-dev \
    libavcodec-extra libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjasper1 libjasper-dev \
    libatlas-base-dev gfortran libeigen3-dev libtbb-dev \
    python-dev python-numpy

script:
  - cd tests/python
  - pytest.py
